version: "3.9"

services:
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
      - "1194:1194/udp"
    cap_add:
      - NET_ADMIN
    environment:
      - EASYRSA_KEY_SIZE=${VPN_EASYRSA_KEY_SIZE}
      - EASYRSA_REQ_CN=${VPN_ENDPOINT_DNS}
    volumes:
      - ${VPN_MOUNT_PATH}:/etc/openvpn
      - ${VPN_MOUNT_PATH}/log:/tmp/openvpn-status.log
    network_mode: host
    restart: unless-stopped
    stop_grace_period: 30s

  openvpn-monitor:
    depends_on:
      - openvpn
    image: ruimarinho/openvpn-monitor
    container_name: openvpn-monitor
    ports:
      - 80:80
    environment:
      OPENVPNMONITOR_DEFAULT_DATETIMEFORMAT: "%%d/%%m/%%Y"
      OPENVPNMONITOR_DEFAULT_LATITUDE: -37
      # OPENVPNMONITOR_DEFAULT_LOGO: logo.jpg
      OPENVPNMONITOR_DEFAULT_LONGITUDE: 144
      OPENVPNMONITOR_DEFAULT_MAPS: True
      OPENVPNMONITOR_DEFAULT_MAPSHEIGHT: 500
      OPENVPNMONITOR_DEFAULT_SITE: Test
      OPENVPNMONITOR_SITES_0_ALIAS: UDP
      OPENVPNMONITOR_SITES_0_HOST: localhost
      OPENVPNMONITOR_SITES_0_NAME: UDP
      OPENVPNMONITOR_SITES_0_PORT: 5555
      OPENVPNMONITOR_SITES_0_SHOWDISCONNECT: True
    network_mode: host
    restart: unless-stopped
    stop_grace_period: 30s
