{
 "title": "1  OpenVPN Server",
 "description": "OpenVPN Server status using Prometheus and OpenVPN exporter ",
 "tags": [ "openvpn" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Top Logins",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(6, sum(count_values(\"connection_time\", count_over_time(openvpn_server_client_received_bytes_total{common_name!=\"UNDEF\"}[1d]))by(common_name))by(common_name)>1)",
     "legendFormat": "{{ common_name }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openvpn_up{job=\"openvpn-metrics\"}",
     "legendFormat": "Status:"
    }
   ]
  },
  {
   "title": "Current OpenVPN Clients",
   "type": "table-old",
   "gridPos": { "h": 21, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(sum(label_replace(openvpn_server_client_received_bytes_total{common_name!=\"UNDEF\"}, \"connection_time\", \"${1}000\", \"connection_time\", \"(.*)\"))by(common_name, connection_time, virtual_address))"
    },
    {
     "expr": "sum(label_replace(openvpn_server_client_sent_bytes_total{common_name!=\"UNDEF\"}, \"connection_time\", \"${1}000\", \"connection_time\", \"(.*)\"))by(common_name, connection_time, virtual_address)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openvpn_openvpn_server_connected_clients",
     "legendFormat": "Clients"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-openvpn_status_update_time_seconds{job=\"openvpn-metrics\"}",
     "legendFormat": "Since Status Update"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(openvpn_server_client_received_bytes_total{common_name=~\"server.*\"}) or absent(count(openvpn_server_client_received_bytes_total{common_name=~\"server.*\"}))-1",
     "legendFormat": "Servers"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(openvpn_server_client_sent_bytes_total[1d]))",
     "legendFormat": "Sent Today"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(openvpn_server_client_received_bytes_total{common_name=~\".*\"}) or absent(count(openvpn_server_client_received_bytes_total{common_name=~\".*\"}))-1",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(openvpn_server_client_received_bytes_total[1d]))",
     "legendFormat": "Recived Today"
    }
   ]
  },
  {
   "title": "Top Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(6, sum(increase(openvpn_server_client_received_bytes_total{common_name!=\"UNDEF\"}[1d])+increase(openvpn_server_client_sent_bytes_total{common_name!=\"UNDEF\"}[1d]))by(common_name))",
     "legendFormat": "{{ common_name }}"
    }
   ]
  },
  {
   "title": "Top 6 Client Network Activity",
   "type": "timeseries",
   "description": "Transmit/Receive",
   "gridPos": { "h": 7, "w": 7, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "-topk(6, sum(rate(openvpn_server_client_received_bytes_total{common_name!=\"UNDEF\"}[2m]))by(common_name))",
     "legendFormat": "{{ common_name }} - Rx"
    },
    {
     "expr": "topk(6, sum(rate(openvpn_server_client_sent_bytes_total{common_name!=\"UNDEF\"}[2m]))by(common_name))",
     "legendFormat": "{{ common_name }} - Tx"
    },
    {
     "expr": "sum(bottomk(scalar(openvpn_openvpn_server_connected_clients)-6, sum(rate(openvpn_server_client_received_bytes_total{common_name!=\"UNDEF\"}[2m]))by(common_name)))",
     "legendFormat": "Rx - Others"
    },
    {
     "expr": "sum(bottomk(scalar(openvpn_openvpn_server_connected_clients)-6, sum(rate(openvpn_server_client_sent_bytes_total{common_name!=\"UNDEF\"}[1m]))by(common_name)))",
     "legendFormat": "Tx - Others"
    }
   ]
  },
  {
   "title": "Traffic Distribution",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(sum(increase(openvpn_server_client_received_bytes_total{common_name!=\"UNDEF\"}[1d])+increase(openvpn_server_client_sent_bytes_total{common_name!=\"UNDEF\"}[1d]))by(common_name))",
     "legendFormat": "{{ common_name }}"
    }
   ]
  },
  {
   "title": "Clients Connected",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(openvpn_openvpn_server_connected_clients)",
     "legendFormat": "Connected OpenVPN Clients"
    }
   ]
  }
 ]
}